# Description:
# This Dockerfile tries to provied a base enviroment for dealing with android related tasks
# for this purpose we need the openjdk and the android sdk

# strongly inspired by
# - https://github.com/banianhost/docker-android/blob/master/Dockerfile
#     (https://github.com/banianhost/docker-android/blob/0fcfbb6bbf730d11c111ed9e7dd8d0eea091b790/Dockerfile)
# - https://github.com/gilesp/docker/blob/master/react_native/Dockerfile
#     (https://github.com/gilesp/docker/blob/887c360e835d7381bb500267937a4371450b9e6d/react_native/Dockerfile)

# 1.Step we need the java openjdk
FROM openjdk:8u131
